source("models/nlma01_poisson regression total.R")
rm(); gc(); source(".Rprofile")
source("models/nlma02_poisson regression urban.R")
rm(); gc(); source(".Rprofile")
source("models/nlma03_poisson regression rural.R")
rm(); gc(); source(".Rprofile")

# source("models/nlmb01_poisson regression total.R")
# rm(); gc(); source(".Rprofile")
source("models/nlmb02_poisson regression urban.R")
rm(); gc(); source(".Rprofile")
source("models/nlmb03_poisson regression rural.R")
rm(); gc(); source(".Rprofile")